### ISSUE TITLE
Display issue if you load a file through drag & drop while "ORAN analysis" view is opened

### ISSUE THREAD

**Issue by Krisscut** [AeroFlorian/netconf-parser#16]
Using NetconfParser 0.6:

See the result of the manipulation in title:
![image](https://github.com/user-attachments/assets/a002bdf0-a773-4b38-a8f5-d7b479fd700c)

I guess because it adds some tree view to the "left" panel, but in this case there was already the oran analysis view opened there !

**Comment by AeroFlorian** [comment]
Thanks, will be fixed
On drag and drop Oran Analysis tab will disappear if it is opened
